# Site settings
title: Offgridly
header-img: img/home-bg.png
email: jessenovotny@gmail.com
copyright_name: jessenovotny
description: > # this means to ignore newlines until "baseurl:"
  Sustainability within reach!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jessenovotny
learn_profile: jessenovotny
email_username: jessenovotny@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
